
services:
  app:
    build: .
    container_name: app
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/alg
    depends_on:
      - db


  db:
    image: 'postgres'
    container_name: 'db'
    expose:
      - '5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: qwe
      POSTGRES_DB: alg


volumes:  # Объявляем все volumes
  postgres_data:
